/**
 * Copies the dependency-free Setup Check modules (and the instrument catalog)
 * into supabase/functions/_shared so the `setup-validation` Edge Function runs
 * the SAME deterministic logic as the app. Deno needs explicit `.ts` import
 * extensions, so relative imports are rewritten.
 *
 *   npm run shared:sync      (a test fails if the copies are out of date)
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

export const SHARED_FILES: [string, string][] = [
  ['src/lib/engines/setupCheck/engine.ts', 'supabase/functions/_shared/setupCheck/engine.ts'],
  ['src/lib/engines/setupCheck/vision.ts', 'supabase/functions/_shared/setupCheck/vision.ts'],
  ['src/lib/engines/setupCheck/rules.ts', 'supabase/functions/_shared/setupCheck/rules.ts'],
  ['src/lib/engines/setupCheck/context.ts', 'supabase/functions/_shared/setupCheck/context.ts'],
  ['src/lib/engines/setupCheck/risk.ts', 'supabase/functions/_shared/setupCheck/risk.ts'],
  ['src/lib/engines/setupCheck/decision.ts', 'supabase/functions/_shared/setupCheck/decision.ts'],
  ['src/lib/engines/setupCheck/events.ts', 'supabase/functions/_shared/setupCheck/events.ts'],
  ['src/lib/engines/setupCheck/icc.ts', 'supabase/functions/_shared/setupCheck/icc.ts'],
  ['src/lib/engines/setupCheck/iccVision.ts', 'supabase/functions/_shared/setupCheck/iccVision.ts'],
  ['src/data/instruments.ts', 'supabase/functions/_shared/setupCheck/instruments.ts'],
];

export const HEADER = '// GENERATED by scripts/sync-setup-check-shared.ts — edit the source under src/, then run `npm run shared:sync`.\n';

export const toDeno = (source: string) => HEADER + source.replace(/(from\s+'\.\/[A-Za-z0-9_-]+)'/g, "$1.ts'");

if (process.argv[1]?.includes('sync-setup-check-shared')) {
  mkdirSync('supabase/functions/_shared/setupCheck', { recursive: true });
  for (const [from, to] of SHARED_FILES) {
    writeFileSync(to, toDeno(readFileSync(from, 'utf8')));
    console.log(`synced ${from} → ${to}`);
  }
}
