// GENERATED by scripts/sync-setup-check-shared.ts — edit the source under src/, then run `npm run shared:sync`.
// SHARED, dependency-free (synced to supabase/functions/_shared/firmRules/monitor.ts).
// Low-cost maintenance of the prop-firm rules database.
//
// A scheduled server job (Edge Function `firm-rules-monitor`, or
// `npm run firm-rules:check`) re-checks the OFFICIAL source pages behind the
// verified rules — never on user visits:
//   1. Only sources that are due are checked (weekly by default), at most
//      `maxPerRun` per run, oldest first.
//   2. Conditional requests (ETag / Last-Modified) — an unchanged page costs
//      one 304 response.
//   3. The page text is normalised and hashed. No AI, no scraping of values.
//   4. A changed hash creates a REVIEW item. Nothing is published: a person
//      re-verifies the rules and publishes a NEW rule version
//      (`npm run firm-rules:publish`), keeping every previous version.
//   5. Blocked / unreachable sources back off exponentially and are reported;
//      the verified data already on file stays as it is.

export const CHECK_INTERVAL_DAYS = 7;
export const MAX_BACKOFF_DAYS = 30;
export const DEFAULT_MAX_PER_RUN = 25;

export type SourceStatus = 'new' | 'unchanged' | 'changed' | 'blocked' | 'unreachable';

export interface MonitoredSource {
  url: string;
  title: string | null;
  firmId: string;
  programIds: string[];
  contentHash: string | null;
  etag: string | null;
  lastModified: string | null;
  lastCheckedAt: string | null;
  nextCheckAt: string | null;
  consecutiveFailures: number;
  lastStatus: SourceStatus;
}

/** Minimal shape of the rules database this module reads (structural — no app imports). */
interface DbLike {
  programs: {
    id: string;
    firmId: string;
    options?: { sources: { url: string; title?: string }[] }[];
    versions: { verification: { sources: { url: string; title?: string }[] }; records?: { sources: { url: string; title?: string }[] }[] }[];
  }[];
}

/** Every official source URL behind the database, with the programs that rely on it. */
export function sourcesFromDatabase(db: DbLike): { url: string; title: string | null; firmId: string; programIds: string[] }[] {
  const map = new Map<string, { url: string; title: string | null; firmId: string; programIds: Set<string> }>();
  const add = (url: string, title: string | undefined, firmId: string, programId: string) => {
    const key = url.split('#')[0];
    const cur = map.get(key) ?? { url: key, title: title ?? null, firmId, programIds: new Set<string>() };
    cur.programIds.add(programId);
    map.set(key, cur);
  };
  for (const p of db.programs) {
    for (const v of p.versions) {
      for (const s of v.verification.sources) add(s.url, s.title, p.firmId, p.id);
      for (const r of v.records ?? []) for (const s of r.sources) add(s.url, s.title, p.firmId, p.id);
    }
    for (const o of p.options ?? []) for (const s of o.sources) add(s.url, s.title, p.firmId, p.id);
  }
  return [...map.values()].map((s) => ({ ...s, programIds: [...s.programIds].sort() })).sort((a, b) => a.url.localeCompare(b.url));
}

/** Sources due for a check now, oldest first, capped per run (cost control). */
export function dueSources(sources: MonitoredSource[], now: Date, maxPerRun = DEFAULT_MAX_PER_RUN): MonitoredSource[] {
  const t = now.getTime();
  return sources
    .filter((s) => !s.nextCheckAt || Date.parse(s.nextCheckAt) <= t)
    .sort((a, b) => (a.lastCheckedAt ? Date.parse(a.lastCheckedAt) : 0) - (b.lastCheckedAt ? Date.parse(b.lastCheckedAt) : 0))
    .slice(0, maxPerRun);
}

/**
 * Page text without markup and volatile noise (scripts, styles, tracking
 * tokens, "updated N days ago", timestamps) so cosmetic changes don't
 * trigger reviews.
 */
export function normalizePageText(html: string): string {
  return html
    .replace(/<(script|style|noscript|svg)[\s\S]*?<\/\1>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&#\d+;|&[a-z]+;/gi, ' ')
    .replace(/\b(updated|written|edited)\b[^.]{0,40}\bago\b/gi, ' ')
    .replace(/\b\d{1,2}:\d{2}(:\d{2})?\s*(am|pm)?\b/gi, ' ')
    .replace(/\b(nonce|csrf|token|session)[-_a-z]*\s*[:=]\s*\S+/gi, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

/** Stable content fingerprint (two FNV-1a passes + length; collision-safe enough for change detection). */
export function pageHash(text: string): string {
  let a = 0x811c9dc5;
  let b = 0x01000193;
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i);
    a = Math.imul(a ^ c, 0x01000193);
    b = Math.imul(b ^ c, 0x811c9dc5) ^ (b >>> 13);
  }
  return `${(a >>> 0).toString(16).padStart(8, '0')}${(b >>> 0).toString(16).padStart(8, '0')}:${text.length}`;
}

export interface FetchOutcome {
  /** HTTP status, or 0 when the request failed (DNS, timeout, TLS…). */
  status: number;
  body?: string;
  etag?: string | null;
  lastModified?: string | null;
}

export interface CheckResult {
  source: MonitoredSource;
  status: SourceStatus;
  /** A person must re-verify the rules backed by this source. */
  reviewNeeded: boolean;
  reason: string;
}

const days = (n: number) => n * 86_400_000;

/** Fold one fetch into the source's state. Never touches rule values. */
export function applyCheck(prev: MonitoredSource, res: FetchOutcome, now: Date): CheckResult {
  const at = now.toISOString();
  const ok = (status: SourceStatus, patch: Partial<MonitoredSource>, reviewNeeded: boolean, reason: string): CheckResult => ({
    source: { ...prev, ...patch, lastCheckedAt: at, nextCheckAt: new Date(now.getTime() + days(CHECK_INTERVAL_DAYS)).toISOString(), consecutiveFailures: 0, lastStatus: status },
    status,
    reviewNeeded,
    reason,
  });
  if (res.status === 304) return ok('unchanged', {}, false, 'Not modified since the last check.');
  if (res.status >= 200 && res.status < 300 && typeof res.body === 'string') {
    const hash = pageHash(normalizePageText(res.body));
    const meta = { contentHash: hash, etag: res.etag ?? null, lastModified: res.lastModified ?? null };
    if (!prev.contentHash) return ok('new', meta, false, 'Baseline recorded for this source.');
    if (hash === prev.contentHash) return ok('unchanged', meta, false, 'Page text unchanged.');
    return ok('changed', meta, true, 'The official page changed — re-verify the rules that cite it before publishing a new version.');
  }
  const failures = prev.consecutiveFailures + 1;
  const blocked = [401, 403, 407, 429, 451].includes(res.status);
  const backoff = Math.min(MAX_BACKOFF_DAYS, CHECK_INTERVAL_DAYS * 2 ** (failures - 1));
  const status: SourceStatus = blocked ? 'blocked' : 'unreachable';
  return {
    source: { ...prev, lastCheckedAt: at, nextCheckAt: new Date(now.getTime() + days(backoff)).toISOString(), consecutiveFailures: failures, lastStatus: status },
    status,
    // Persistent failure is worth a human look (the page may have moved); the verified data stays as it is.
    reviewNeeded: failures >= 3,
    reason: `${blocked ? 'Blocked' : 'Unreachable'} (${res.status || 'network error'}) — next try in ${backoff} days.${failures >= 3 ? ' Failing repeatedly: check whether the page moved.' : ''}`,
  };
}

/** A new monitored source (first check records a baseline, it doesn't flag a review). */
export const newSource = (s: { url: string; title: string | null; firmId: string; programIds: string[] }): MonitoredSource => ({
  ...s,
  contentHash: null,
  etag: null,
  lastModified: null,
  lastCheckedAt: null,
  nextCheckAt: null,
  consecutiveFailures: 0,
  lastStatus: 'new',
});
